### ISSUE TITLE
branch qsv-2.8.1 can't set IdrInterval for hevc encoder

### ISSUE THREAD

**Issue by andrewmabc** [Intel-FFmpeg-Plugin/Intel_FFmpeg_plugins#11]
There is no way to set IdrInterval for hevc encoder like h264.

For example,

/usr/local/bin/ffmpeg -i input.mp4 -acodec libfdk_aac -ac 2 -b:a 32k -vcodec hevc_qsv -s 640x360 -b:v 400k -g 250 -f mp4 output.mp4

There is only one key frame in output.mp4

And there is no 'IdrInterval' option for hevc_qsv, like h264_qsv.

**Comment by lizhong1008** [comment]
It has been supported by https://github.com/FFmpeg/FFmpeg. 
Could you try
https://github.com/FFmpeg/FFmpeg/commit/077011b5af2b3150efc52a9b58f5ef9bb0235087 and 
https://github.com/FFmpeg/FFmpeg/commit/98afe3fb71afd4a18009924aaba56bc577bbd400 ?

**Comment by andrewmabc** [comment]
could you help merge the changes into branch qsv-2.8.1?

**Comment by lizhong1008** [comment]
Patch merged. Please let me know if it can't work as your expectation.

**Comment by andrewmabc** [comment]
Thanks. The patch works.
