### ISSUE TITLE
Failed to inject frame into filter network: Cannot allocate memory

### ISSUE THREAD

**Issue by YaboWei** [Intel-FFmpeg-Plugin/Intel_FFmpeg_plugins#14]
Hi, all
I test scale_qsv use branch intel_ffmpeg-3.4.1, ffmpeg print "Cannot allocate memory" error after 20 frames.
command line:
./ffmpeg -re -hwaccel qsv -vcodec h264_qsv  -i ~/samples/assassin_st4_1080p30fps.flv         -vf scale_qsv=1280:720 -vcodec h264_qsv -profile:v high -b:v 1000k -maxrate:v 3000k -bufsize:v 3000k -g 50 -an -f flv -y ~/output.264
my input is 1920x1080, h264
thanks!

CPU: Intel(R) Core(TM) i7-6770HQ
OS: CentOS Linux release 7.2.1511 (Core)
kernel: 3.10.0-327.el7.x86_64
MSS: MediaServerStudioProfessionalEvaluation2017

**Comment by lizhong1008** [comment]
@YaboWei , intel_ffmpeg_3.4.1 is a developing branch, it is not stable right now. 
Do you think using intel_plugings_3.3.1 branck is ok to you?

**Comment by YaboWei** [comment]
@lizhong1008 Do you means origin/intel_plugins-3.3.1?

**Comment by YaboWei** [comment]
Got it!, intel_plugings_3.3.1 is ok to me.
thanks!
