### ISSUE TITLE
what's the difference between branch intel_ffmpeg-3.4.1 and intel_plugins-3.3.1?

### ISSUE THREAD

**Issue by andrewmabc** [Intel-FFmpeg-Plugin/Intel_FFmpeg_plugins#17]
Hi,

I have one question about active branch.

what's the difference between branch intel_ffmpeg-3.4.1 and intel_plugins-3.3.1?

Why does the branch qsv-3.2.2 become not active? Intel don't support the branch any more. Is that right?

Thanks!

B.R.

Andrew

**Comment by lizhong1008** [comment]
@andrewmabc, thanks for your close attention. intel_ffmpeg_3.4.1 is forked from official ffmpeg 3.4.1, We are preparing to release it as a new version, adding some intel special patches. The development and testing work of  intel_ffmpeg_3.4.1 is WIP, and it is not stable enough now. If you want a latest version, intel_plugins-3.3.1 is recommended. 
qsv-3.2.2 is also supported and please let me know if you have any issue.

**Comment by andrewmabc** [comment]
But in the website of 'https://github.com/Intel-FFmpeg-Plugin/Intel_FFmpeg_plugins/branches', there are three active branches, including intel_ffmpeg-3.4.1, qsv-2.8.1 and intel_plugins-3.3.1. 

But the branch qsv-3.2.2 belongs to stale branches. Does it mean Intel don't support qsv-3.2.2 like qsv-2.6.3.

**Comment by lizhong1008** [comment]
It should produced automatically by github, these there branches have patches merged recently. 
Please refer our wiki: https://github.com/Intel-FFmpeg-Plugin/Intel_FFmpeg_plugins/wiki

**Comment by andrewmabc** [comment]
what's the difference between branch intel_plugins-3.3.1 and qsv-3.2.2?

**Comment by lizhong1008** [comment]
It just like the difference between ffmpeg official branch 3.3.1 and 3.2.2.

**Comment by andrewmabc** [comment]
Thanks a lot!
