### ISSUE TITLE
It will be core dumped while do vpp overlay or overlay_alpha

### ISSUE THREAD

**Issue by wangzj0601** [Intel-FFmpeg-Plugin/Intel_FFmpeg_plugins#20]
Test Env:
============================================
Platfrom: SKL
OS:   CentOS 7.3.1611
Kernel version: 4.4.0
VPG Driver: 16.5.2.64009-ubit
Mediasdk:   MediaServerStudioEssentials2017R3
FFMPEG:    3cc8fa1431b9e2ce7d93cefea9bb1c47ccf5c10f(branch:intel_ffmpeg-3.4.1)
                  repo: https://github.com/Intel-FFmpeg-Plugin/Intel_FFmpeg_plugins.git

Reproduce Steps:
============================================
1. build the environment as above
2. ffmpeg -hwaccel qsv -c:v h264_qsv -i /media/ffmpeg_stream_dcg//vintage_car_1920x1080_24p_4_0_1920x1080p_71frames.264 -vf 'movie=/media/ffmpeg_stream_dcg//001.png,hwupload,format=qsv[wm];[0:v][wm]overlay_qsv=x=W*0.85:y=H*0.03:w=96:h=27' -c:v h264_qsv -y /home/harddisk_sdb2/dcgm-ffmpeg-qsv-validation/output/VPP/overlay/vpp_overlay_1920x1080P_watermark.h264
or
ffmpeg -hwaccel qsv -c:v h264_qsv -i /media/ffmpeg_stream_dcg//vintage_car_1920x1080_24p_4_0_1920x1080p_71frames.264 -vf 'movie=/media/ffmpeg_stream_dcg//001.png,hwupload,format=qsv[wm];[0:v][wm]overlay_qsv=x=W*0.85:y=H*0.03:w=96:h=27:alpha=200' -c:v h264_qsv -y /home/harddisk_sdb2/dcgm-ffmpeg-qsv-validation/output/VPP/overlay_alpha/vpp_overlay_1920x1080P_apha_200.h264
3. the command will be core dumped

**Comment by ruiling** [comment]
@wangzj0601 #22 should fix this issue, please have a try.

**Comment by wangzj0601** [comment]
This issue can be fixed with ruiling's patch with commit 453c3c384f1c956ce1f676edf73950ce0ed3f5e9, so close it.
