### ISSUE TITLE
[AVC encode] option recoverypointSEI is not support 

### ISSUE THREAD

**Issue by wangzj0601** [Intel-FFmpeg-Plugin/Intel_FFmpeg_plugins#29]
Test Env:
Platfrom: SKL
OS: CentOS 7.3.1611
Kernel version: 4.4.0
VPG Driver: 16.5.2.64009-ubit
Mediasdk: MediaServerStudioEssentials2017R3
FFMPEG: 0e9c48d (branch:intel_ffmpeg-3.4.1)
repo: https://github.com/Intel-FFmpeg-Plugin/Intel_FFmpeg_plugins.git

Reproduce Steps:
1.build the environment as above
2.ffmpeg -f rawvideo -video_size 1920x1080 -pix_fmt nv12 -i /root/media_streams/ffmpeg_streams/ffmpeg_yuv_dcg//123_217frame_1920x1080_blue_sky.yuv -init_hw_device qsv:hw -c:v h264_qsv -recoverypointSEI 1 -y /home/harddisk_sdb2/dcgm-ffmpeg-qsv-validation/output/H264_Encode/H264e_recoverypointSEI/H264e_recoverypointSEI_1080P.h264
3.it reminds that "Unrecognized option 'recoverypointSEI'"

**Comment by lizhong1008** [comment]
It is named as "recovery_point_sei" now.
