### ISSUE TITLE
ffmpeg decode hevc failed

### ISSUE THREAD

**Issue by YaboWei** [Intel-FFmpeg-Plugin/Intel_FFmpeg_plugins#3]
Hi, I get some hevc decode problems：

1， ffmpeg and MSS sample decode 10bit hevc failed；

2， I have a 8bit hevc, MSS sample decode success, but ffmpeg decode failed; below is the 8bit hevc:

[http://pan.baidu.com/s/1hsOMdU0](url)

**Comment by hzhan80** [comment]
Hi YaboWei,
     1. hevc 10bit haven't been supported by MSS yet. and  so decoder will fail.
     2. please try latest code with branch qsv-3.2.2  in this repo. We have some fix with HEVC_qsv codec 
         git clone  https://github.com/Intel-FFmpeg-Plugin/Intel_FFmpeg_plugins.git
         git checkout origin/qsv-3.2.2 -b 3.2.2

**Comment by YaboWei** [comment]
Hi,
My code is already the newest. 
Thanks!

**Comment by hzhan80** [comment]
OK. We will download the clip and debug the issue asap. 
thanks

**Comment by hzhan80** [comment]
Issue is fixed from commit "b178ad45a09da213ad075b24ca3498f240bbf279" in qsv-3.2.2 branch.
