### ISSUE TITLE
Linking issue with release 3.4.1.0

### ISSUE THREAD

**Issue by ghost** [Intel-FFmpeg-Plugin/Intel_FFmpeg_plugins#31]
Hi,

this new release looks very nice! It's quite stable now.
Though, I have an issue during linking:

LD      ffmpeg_g
libavutil/libavutil.a(hwcontext_vaapi.o): In function `vaapi_device_create':
hwcontext_vaapi.c:(.text+0x1cd3): undefined reference to `vaSetErrorCallback'
hwcontext_vaapi.c:(.text+0x1ce3): undefined reference to `vaSetInfoCallback'
collect2: error: ld returned 1 exit status

I have to force CONFIG_VAAPI_1  to 0 in config.h ( I am using libva.so.1 -> libva.so.1.9900.0 from the official MediaSDK 2017R3 package).

Thanks

**Comment by lizhong1008** [comment]
CONFIG_VAAPI_1 will be (and only be) enabled when libva version is libva2.0 (see the commit commit 9c7a71145b88e56cb5f67c66f6d27c20c8d06165
Author: Mark Thompson <sw@jkqxz.net>
Date:   Sun Oct 1 22:51:07 2017 +0100

    configure: Add config option for libva2 (VAAPI 1)
). 

I am not sure why it is enabled on your side. but it is 0 on my side. Could you double check some info:
1. could you help to check what is the value of VA_MAJOR_VERSION in va_version.h?
2.  vainfo to make sure : VA-API version: 0.99 
3. make sure you have only one va.h/va_version.h files.

**Comment by lizhong1008** [comment]
@ViGill , any comments?

**Comment by lizhong1008** [comment]
Close this issue since no feedback.
