### ISSUE TITLE
[AVC decode] AVC decoding fails with some streams (it works with 3.3.1 branch)

### ISSUE THREAD

**Issue by ghost** [Intel-FFmpeg-Plugin/Intel_FFmpeg_plugins#32]
Hi,

on FFmpeg-3.4.1 branch, decoding of some H264 fails with error:
[h264_qsv @ 0xc86700] Error during QSV decoding.: incompatible video parameters (-14)

it works on FFmpeg-3.3.1 branch.
File is attached.
[decoding_fails.gz](https://github.com/Intel-FFmpeg-Plugin/Intel_FFmpeg_plugins/files/1970127/decoding_fails.gz)

Command:
/usr/local/bin/ffmpeg -hwaccel qsv -init_hw_device qsv=myqsv -filter_hw_device myqsv -qsv_device /dev/dri/renderD128 -c:v h264_qsv -i ./decoding_fails.mp4 -an -vcodec h264_qsv -preset medium -profile:v baseline -level:v 22 -vf [main]hwupload,vpp_qsv=w=512:h=288[out] -y out.mp4

Thanks

**Comment by lizhong1008** [comment]
Reproduced.  Look like it is relative to the coded bitstream.  
When I use similar command for another video (bbb_sunflower_1080p_30fps_normal.mp4), everything is ok. 
Will check more detail soon.

**Comment by ghost** [comment]
Thanks! looking forward to your feedback.

**Comment by lizhong1008** [comment]
@ViGill ,  I found the video decoding_fails.mp4 is not correct. It is 1080p video with level_idc=4. 
In this case, the largest reference frame is 4. But decoding_fails.mp4 has 5 reference frames.  Then MSDK decoding failed when it checked this.
FFmpeg-3.3.1 branch can decoding it because it is using MSDK's parser can change the level_idc to 5 internally. But FFmpeg-3.4.1 is using FFmpeg's parser.

**Comment by ghost** [comment]
Hi,

ok understood.. but it looks like we have a lot of these files as input. I guess encoder don't report properly.
Is there a chance to add an option to use MSDK parser ?

Thanks

**Comment by lizhong1008** [comment]
Hi ViGill:
     No such a option and we don't have a plan to support this because FFmpeg-3.4.1 qsv decoding should keep same as FFmpeg mainline. 
    I guess a hack way can solve your problem by always set a  largest level_idc to MSDK ( I don't like such a patch (and won't merge it) but it should be a workable workaround to fix your issue.):
```
diff --git a/libavcodec/qsvdec.c b/libavcodec/qsvdec.c
index 1c45443..3e61e53 100644
--- a/libavcodec/qsvdec.c
+++ b/libavcodec/qsvdec.c
@@ -175,6 +175,8 @@ static int qsv_decode_init(AVCodecContext *avctx, QSVContext *q, AVPacket *avpkt
         param.mfx.CodecId      = ret;
         param.mfx.CodecProfile = ff_qsv_profile_to_mfx(avctx->codec_id, avctx->profile);
         param.mfx.CodecLevel   = avctx->level == FF_LEVEL_UNKNOWN ? MFX_LEVEL_UNKNOWN : avctx->level;
+        if (avctx->codec_id == AV_CODEC_ID_H264)
+           param.mfx.CodecLevel = MFX_LEVEL_AVC_52;
```

**Comment by ghost** [comment]
Ok thanks :)
I guess that it will use a lot more memory right ? It will always alloc the max possible mem...
I think the GPU uses the system RAM which is 64GB, so it should be fine.

**Comment by lizhong1008** [comment]
@ViGill , I don't think it will use more memory because we haven't change the reference frame number.
