### ISSUE TITLE
[h264_qsv @ 0x2dc0680] Decoding pixel format '(null)' is not supported

### ISSUE THREAD

**Issue by zywu31** [Intel-FFmpeg-Plugin/Intel_FFmpeg_plugins#33]
MSDK : 2018R1
FFMPEG Version: Intel_FFmpeg_plugins 3.4.1
command line : ./ffmpeg -hwaccel qsv -c:v h264_qsv -re -i /usr/1.ts -look_ahead 1 -c:v h264_qsv -preset fast -b:v 2000k -c:a copy -f mpegts 'udp://192.168.2.112:20000?pkt_size=1316&ttl=255'

[h264_qsv @ 0x2dc0680] Decoding pixel format '(null)' is not supported
Error while decoding stream #0:1: Function not implemented
[NULL @ 0x2dad1e0] SPS unavailable in decode_picture_timing
[NULL @ 0x2dad1e0] non-existing PPS 0 referenced
[h264_qsv @ 0x2dc0680] Decoding pixel format '(null)' is not supported
Error while decoding stream #0:1: Function not implemented
[NULL @ 0x2dad1e0] SPS unavailable in decode_picture_timing
[NULL @ 0x2dad1e0] non-existing PPS 0 referenced
[h264_qsv @ 0x2dc0680] Decoding pixel format '(null)' is not supported
Error while decoding stream #0:1: Function not implemented
[NULL @ 0x2dad1e0] SPS unavailable in decode_picture_timing
[NULL @ 0x2dad1e0] non-existing PPS 0 referenced
[h264_qsv @ 0x2dc0680] Decoding pixel format '(null)' is not supported
Error while decoding stream #0:1: Function not implemented

**Comment by turingyao** [comment]
I met the same problem. Is the problem fixed?

**Comment by lizhong1008** [comment]
@zywu31 @turingyao  please upload your video clips.  Else we can't reproduce your issue.

**Comment by zywu31** [comment]
------------------ 原始邮件 ------------------
发件人: "LiZhong"<notifications@github.com>;
发送时间: 2018年8月10日(星期五) 上午8:53
收件人: "Intel-FFmpeg-Plugin/Intel_FFmpeg_plugins"<Intel_FFmpeg_plugins@noreply.github.com>;
抄送: "START"<1715921@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [Intel-FFmpeg-Plugin/Intel_FFmpeg_plugins] [h264_qsv @ 0x2dc0680]Decoding pixel format '(null)' is not supported (#33)




@zywu31 @turingyao  please upload your video clips.  Else we can't reproduce your issue.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


从QQ邮箱发来的超大附件

cctv2.ts (25.27M, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=0c3037320f940ecae01e2d321537571b55090656000356071c560f0b031a510501011a5003555019525502025653010300010e0a333f6557524441001d4316340c&t=exs_ftn_download&code=107237e4

**Comment by lizhong1008** [comment]
@zywu31 , tried ffmpeg software decoder, will also report error.  Please double-confirm this video is correct.
