### ISSUE TITLE
resolution conversion fail

### ISSUE THREAD

**Issue by turingyao** [Intel-FFmpeg-Plugin/Intel_FFmpeg_plugins#34]
**Hardware:**
N3450

**System:**
4.13.0-43-generic #48~16.04.1-Ubuntu SMP Thu May 17 12:56:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Command:**
ffmpeg -hwaccel qsv -vcodec h264_qsv -i 1.mp4 -vcodec h264_qsv -s 1920x1080 -y -acodec copy out1.mp4

**Error:**
ffmpeg version qsv-3.4.1.0-1-g7707fb6 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.9) 20160609
  configuration: --prefix=/home/box/ffmpeg-build --pkg-config-flags=--static --extra-libs='-lpthread -lm' --bindir=/home/box/bin --enable-gpl --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-nonfree --enable-libmfx
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '1.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    title           : Media Server
    encoder         : Lavf56.40.101
  Duration: 00:01:00.00, start: 0.000000, bitrate: 6165 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuvj420p(pc, bt709), 2688x1520 [SAR 1:1 DAR 168:95], 6122 kb/s, 20 fps, 20 tbr, 10240 tbn, 40 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 8000 Hz, mono, fltp, 39 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (h264_qsv) -> h264 (h264_qsv))
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
Impossible to convert between the formats supported by the filter 'Parsed_null_0' and the filter 'auto_scaler_0'
Error reinitializing filters!
Failed to inject frame into filter network: Function not implemented
Error while processing the decoded data for stream #0:0
Conversion failed!

**Comment by lizhong1008** [comment]
@turingyao , why open this issue and then close it? has it been root caused and fixed?

**Comment by turingyao** [comment]
Hi @lizhong1008 , I found that I should use -vf 'vpp_qsv=w=1920:h=1080' instead of -s 1920x1080

**Comment by lizhong1008** [comment]
@turingyao  got it. Thanks
