### ISSUE TITLE
About FFMPEG Latest Version 4.0 Support ？

### ISSUE THREAD

**Issue by littleflowercatcat** [Intel-FFmpeg-Plugin/Intel_FFmpeg_plugins#35]
We Update MSS SDK : MediaServerStudioEssentials2018R1, But with FFMPEG4.0 can not be used，So when can support FFMPEG 4.0?

The following is the detailed version information：

--------------------------
Hardware readiness checks:
--------------------------
 [ OK ] Processor name: Intel(R) Xeon(R) CPU E3-1585 v5 @ 3.50GHz
 [ INFO ] Intel Processor
 [ INFO ] Processor brand: Xeon
 [ INFO ] Processor arch: Skylake
--------------------------
OS readiness checks:
--------------------------
 [ INFO ] GPU PCI id     : 193A
 [ INFO ] GPU description: SKL SRV GT4e
 [ OK ] GPU visible to OS
 [ INFO ] no nomodeset in GRUB cmdline (good)
 [ INFO ] Linux distro   : CentOS Linux 7.4.1708
 [ INFO ] Linux kernel   : 3.10.0-693.el7.x86_64
 [ INFO ] glibc version  : 2.17
 [ INFO ] Linux distro suitable for Generic install
 [ INFO ] gcc version    : 4.8.5-28) (>=4.8.2 suggested)
--------------------------
Media Server Studio Install:
--------------------------
 [ OK ] user in video group
 [ OK ] libva.so.1 found
 [ INFO ] Intel iHD used by libva
 [ OK ] vainfo reports valid codec entry points
 [ INFO ] i915 driver in use by Intel video adapter
 [ OK ] /dev/dri/renderD128 connects to Intel i915
--------------------------
Component Smoke Tests:
--------------------------
 [ OK ] Media SDK HW API level:1.25
 [ OK ] Media SDK SW API level:1.25
 [ OK ] OpenCL check:platform:Intel(R) OpenCL GPU OK CPU OK

**FFMPEG version is 4.0 release, But have some error:**

[root@localhost ffmpeg-4.0]# ./ffmpeg -v verbose -i ~/demo_2pass.mp4 -vcodec h264_qsv -f mp4 -y xx.mp4
ffmpeg version 4.0 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 4.8.5 (GCC) 20150623 (Red Hat 4.8.5-28)
  configuration: --enable-version3 --enable-gpl --enable-nonfree --enable-libmfx
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
  libpostproc    55.  1.100 / 55.  1.100
[h264 @ 0x2094e80] Reinit context to 1920x1088, pix_fmt: yuv420p
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/root/demo_2pass.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf57.83.100
  Duration: 00:00:10.02, start: 0.000000, bitrate: 4807 kb/s
    Stream #0:0(eng): Video: h264 (High), 1 reference frame (avc1 / 0x31637661), yuv420p(left), 1920x1080 (1920x1088) [SAR 1:1 DAR 16:9], 5198 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 112 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (h264_qsv))
  Stream #0:1 -> #0:1 (aac (native) -> aac (native))
Press [q] to stop, [?] for help
[graph_1_in_0_1 @ 0x235ef40] tb:1/48000 samplefmt:fltp samplerate:48000 chlayout:0x3
[h264 @ 0x209a180] Reinit context to 1920x1088, pix_fmt: yuv420p
[graph 0 input from stream 0:0 @ 0x29b3680] w:1920 h:1080 pixfmt:yuv420p tb:1/12800 fr:25/1 sar:1/1 sws_param:flags=2
[auto_scaler_0 @ 0x2a87700] w:iw h:ih flags:'bicubic' interl:0
[format @ 0x2a85380] auto-inserting filter 'auto_scaler_0' between the filter 'Parsed_null_0' and the filter 'format'
[auto_scaler_0 @ 0x2a87700] w:1920 h:1080 fmt:yuv420p sar:1/1 -> w:1920 h:1080 fmt:nv12 sar:1/1 flags:0x4
[h264_qsv @ 0x2098a00] Initialized an internal MFX session using hardware accelerated implementation
[h264_qsv @ 0x2098a00] Using the variable bitrate (VBR) ratecontrol method
[h264_qsv @ 0x2098a00] MFMode:2
[h264_qsv @ 0x2098a00] Encoder will work with partial HW acceleration
[h264_qsv @ 0x2098a00] Error initializing the encoder: invalid video parameters (-15)
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
[aac @ 0x209a880] Qavg: 41108.051
[aac @ 0x209a880] 2 frames left in the queue on closing
Conversion failed!

**Comment by lizhong1008** [comment]
Any special feature required for FFmpeg4.0?  Is qsv-3.4.1.0 release version ok?

**Comment by littleflowercatcat** [comment]
@lizhong1008 Thank you for your response。

We need "_overlay_qsv_" feature. The scene used is ： one source file, add Watermark，N output file

for Intel_FFmpeg_plugins-qsv-3.4.1.0, test two way cmdline:

a. `/ffmpeg -v verbose -i ~/src1080.mp4 -i logo.png -init_hw_device qsv=foo -filter_hw_device foo -filter_complex '[0:v:0]format=pix_fmts=yuv420p,yadif,split=1[vtmp10],[vtmp10]vpp_qsv=w=1280:h=720[vtmp20],[vtmp20]setdar=dar=16/9[vout10],[1:v:0]scale=1280*iw/1920:-1[logo100],[vout10][logo100]overlay_qsv=x_expr=25:y_expr=25[vout0]' -map [vout0]  -c:v h264_qsv -preset veryslow -vb 800k -g 50 -an -f mp4 -y out.mp4`

**but have error ========>**

[h264 @ 0x1ff7760] Reinit context to 1920x1088, pix_fmt: yuv420p
[Parsed_scale_5 @ 0x23b2a60] w:1280*iw/1920 h:-1 flags:'bilinear' interl:0
[graph 0 input from stream 0:0 @ 0x23b58e0] w:1920 h:1080 pixfmt:yuv420p tb:1/25 fr:25/1 sar:1/1 sws_param:flags=2
[graph 0 input from stream 1:0 @ 0x23b5c20] w:300 h:88 pixfmt:rgba tb:1/25 fr:25/1 sar:0/1 sws_param:flags=2
[Parsed_setdar_4 @ 0x23b2300] w:1280 h:720 dar:16/9 sar:1/1 -> dar:16/9 sar:1/1
[Parsed_scale_5 @ 0x23b2a60] w:300 h:88 fmt:rgba sar:0/1 -> w:200 h:59 fmt:bgra sar:0/1 flags:0x2
[Parsed_overlay_qsv_6 @ 0x23b32e0] [framesync @ 0x23b33e8] Selected 1/25 time base
[Parsed_overlay_qsv_6 @ 0x23b32e0] [framesync @ 0x23b33e8] Sync level 2
[Parsed_overlay_qsv_6 @ 0x23b32e0] Input[0] is of nv12, rect[0,0,1280,720].
[Parsed_overlay_qsv_6 @ 0x23b32e0] Input[1] is of bgra, rect[25,25,200,59].
[h264_qsv @ 0x1ffaee0] Using the variable bitrate (VBR) ratecontrol method
[h264_qsv @ 0x1ffaee0] profile: high; level: 31
[h264_qsv @ 0x1ffaee0] GopPicSize: 50; GopRefDist: 4; GopOptFlag: closed ; IdrInterval: 0
[h264_qsv @ 0x1ffaee0] TargetUsage: 1; RateControlMethod: VBR
[h264_qsv @ 0x1ffaee0] InitialDelayInKB: 150; TargetKbps: 800; MaxKbps: 1200
[h264_qsv @ 0x1ffaee0] NumSlice: 1; NumRefFrame: 3
[h264_qsv @ 0x1ffaee0] RateDistortionOpt: OFF
[h264_qsv @ 0x1ffaee0] RecoveryPointSEI: OFF IntRefType: 0; IntRefCycleSize: 0; IntRefQPDelta: 0
[h264_qsv @ 0x1ffaee0] MaxFrameSize: 345600; MaxSliceSize: 0;
[h264_qsv @ 0x1ffaee0] BitrateLimit: ON; MBBRC: OFF; ExtBRC: OFF
[h264_qsv @ 0x1ffaee0] Trellis: auto
[h264_qsv @ 0x1ffaee0] RepeatPPS: ON; NumMbPerSlice: 0; LookAheadDS: off
[h264_qsv @ 0x1ffaee0] AdaptiveI: unknown; AdaptiveB: unknown; BRefType: off
[h264_qsv @ 0x1ffaee0] MinQPI: 0; MaxQPI: 0; MinQPP: 0; MaxQPP: 0; MinQPB: 0; MaxQPB: 0
[h264_qsv @ 0x1ffaee0] Entropy coding: CABAC; MaxDecFrameBuffering: 3
[h264_qsv @ 0x1ffaee0] NalHrdConformance: OFF; SingleSeiNalUnit: ON; VuiVclHrdParameters: OFF VuiNalHrdParameters: OFF
Output #0, mp4, to 'out.mp4':
  Metadata:
    major_brand     : avc1
    minor_version   : 0
    compatible_brands: avc1mp42
    encoder         : Lavf57.83.100
    Stream #0:0: Video: h264 (h264_qsv), 1 reference frame (avc1 / 0x31637661), nv12, 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 800 kb/s, 25 fps, 12800 tbn, 25 tbc (default)
    Metadata:
      encoder         : Lavc57.107.100 h264_qsv
    Side data:
      cpb: bitrate max/min/avg: 0/0/800000 buffer size: 0 vbv_delay: -1
**[Parsed_overlay_qsv_6 @ 0x23b32e0] Sync failed.
Error marking filters as finished
Conversion failed!**

b. `./ffmpeg -v verbose -hwaccel qsv -c:v h264_qsv -i ~/src1080.mp4 -c:v h264_qsv -vb 800k -an -vf "vpp_qsv=framerate=23:w=1280:h=720[v];movie=logo.png,hwupload,format=qsv[wm];[v][wm]overlay_qsv=x_expr=25:y_expr=25" -f mp4  -y out.mp4`

is OK.

So, Like the difference between the two， Why ???
**-filter_complex
-vf**

**Comment by lizhong1008** [comment]
@pythonsan 1.  For the fail case of ffmpeg 4.0, could you please create a ticket on https://trac.ffmpeg.org/ ? 
2. For the fail case of qsv-3.4.1.0:  a:please simply your command as possible as you can. b. I see you are using sofeware scaler but without hwupload (scale=1280*iw/1920), maybe you can try to use scale_qsv instead.

**Comment by littleflowercatcat** [comment]
@lizhong1008 Thank you for your suggest :-)

We have successfully used the **_overlay_qsv_** features in the FFMPEG4.0 (git newest)version & Intel_FFmpeg_plugins-qsv-3.4.1.0, there are two kinds of error summary : 

A. can not use advanced syntax filter option "**_filter_complex_**",  must use "**_-vf_**"
B. must add specific parameters  "**_-hwaccel qsv -c:v h264_qsv_**"  before input file (-i src.mp4)

But I don't know the reasons for these errors  :-(

**Comment by lizhong1008** [comment]
@pythonsan "filter_complex" can be used, see the example: https://github.com/Intel-FFmpeg-Plugin/Intel_FFmpeg_plugins/commit/7707fb6fc16738923d8f3498c4d2785a52ffc553 . 
"-hwaccel qsv -c:v h264_qsv" can make sure the video will be decoded to gpu memory instead of system memory. 
In FFmpeg 4.0, system memory path is broken (just like your command  ./ffmpeg -v verbose -i ~/demo_2pass.mp4 -vcodec h264_qsv -f mp4 -y xx.mp4 ), it is a bug since qsv-3.4.1.0 works well.  Would better you can create a tikect on https://trac.ffmpeg.org/ , and I will reply you there and fix it for ffmpeg 4.0.

**Comment by littleflowercatcat** [comment]
@lizhong1008 
example: 7707fb6, can exec ok, but can not be used with overlay_qsv (add Watermark). 
This is cmdline for Intel_FFmpeg_plugins-qsv-3.4.1.0 : 

`./ffmpeg -v verbose -y -hwaccel qsv -c:v h264_qsv -i ~/src1080.mp4 -i logo.png \
-filter_complex "[0]split=2[s1][s2]; [s1]scale_qsv=1280:720[o1]; [s2]scale_qsv=960:540[o2];
         [o1] [1] overlay_qsv=x_expr=25:y_expr=25[v1]; [o2] [1] overlay_qsv=x_expr=25:y_expr=25[v2]" \
        -map [v1]  -c:v h264_qsv -b:v 800k -an  -f mp4  ~/mf.hd.mp4 \
        -map [v2]  -c:v h264_qsv -b:v 600k  -an -f mp4  ~/mf.sd.mp4`

> [Parsed_overlay_qsv_3 @ 0x2a579e0] QSVVPP gets a wrong frame.
> [Parsed_overlay_qsv_3 @ 0x2a579e0] Failed to submit frame on input[1]
> Error while filtering: Cannot allocate memory
> Failed to inject frame into filter network: Cannot allocate memory
> Error while processing the decoded data for stream #1:0
> Conversion failed!

I will submit a ticket after this problem is solved, thanks ~

**Comment by lizhong1008** [comment]
@pythonsan I saw you has close this issue. Has it been resolved?   For the FFmpeg 4.0 failed case of "./ffmpeg -v verbose -i ~/demo_2pass.mp4 -vcodec h264_qsv -f mp4 -y xx.mp4" , please refer my comment on https://trac.ffmpeg.org/ticket/7030#comment:21

**Comment by littleflowercatcat** [comment]
@lizhong1008 Thank you for your reply ~  we used intel-ffmpeg-3.4.1.0 & -vf option workaround this problem.
