### ISSUE TITLE
[3.3.1] ffmpeg-qsv h.264 ignores -bufsize:v option

### ISSUE THREAD

**Issue by dvrogozh** [Intel-FFmpeg-Plugin/Intel_FFmpeg_plugins#39]
Running:
```
ffmpeg \
  -hwaccel qsv -c:v h264_qsv -i any_stream.264 \
  -force_key_frames source -force_idr 1 -c:v h264_qsv \
  -b:v 2000k -bufsize:v 3000k -preset medium -bf 1 -g 250 \
  -look_ahead 0 -an qsv_idr.264
```

I see that `-bufsize:v 3000k` is simply ignored. This actually triggers an error described in #36 (though there is still a bug in mediasdk, I mean that even with ignored bufsize:v #36 should not have happened).

**Comment by lizhong1008** [comment]
fixed as  8c632d7
