### ISSUE TITLE
There is no audio frame for the 1st 10 seconds when ffmpeg does normal transcoding

### ISSUE THREAD

**Issue by andrewmabc** [Intel-FFmpeg-Plugin/Intel_FFmpeg_plugins#4]
Hi,

I have found a bug for branch 'qsv-3.2.2'. ffmpeg does normal transcoding, such as

/usr/local/bin/ffmpeg -i oneClip/bigbang.S06E20.1min.flv -acodec libfdk_aac -ac 2 -b:a 48k -vcodec libx264 -b:v 2000k -s 960x720 -g 25 -r 25.0 -f flv ./bigbang.S06E20.1min.test.flv

Then, output file has no audio frame for the 1st 10 seconds. The test clips can be downloaded from the following URL link:
https://drive.google.com/file/d/0Bx1RhuOwoy_Hc1lQdUxxT0RlRXM/view?usp=sharing

Or you can use any clip to check the bug.

I read part of source code, and find audio stream's time stamp is incorrect at the beginning. The reason is that, the logic of calling init_output_stream() has changed, which will invoke flv_write_header(), which will change av streams' time stamp.

---------------------------------------------------------------------------------------
SHA-1: c876b96e689b648a952c3a4361ac3c60c0234729

* FFmpeg: init filtergraphs only after we have a frame on each input.

Signed-off-by: ChaoX A Liu <chaox.a.liu@intel.com>
---------------------------------------------------------------------------------------
I found the version of 'SHA-1: c876b96e689b648a952c3a4361ac3c60c0234729' begins have the bug.

Please check the bug, and fix it as soon as possible.

Thanks!

Regards

Andrew

**Comment by hzhan80** [comment]
issue is fixed in qsv-3.2.2 branch with commit “7ebfb616c0c2f89e0dda8ec28bb55bea55d7c14e"
