### ISSUE TITLE
[3.3.1] favor -bufsize:v option and remove custom qsv h.264 -buffer_size

### ISSUE THREAD

**Issue by dvrogozh** [Intel-FFmpeg-Plugin/Intel_FFmpeg_plugins#41]
https://github.com/Intel-FFmpeg-Plugin/Intel_FFmpeg_plugins/blob/994fc61d5272cc74e1ad1294e0fe865bc393db74/libavcodec/qsvenc_h264.c#L106

There is already an option for this: -bufsize:v, defined globally which imho should be favored. Please, do either of 2 things:
1. Either support -bufsize:v (#39) and remove custom -buffer_size completely (not done)
2. Or **publish** document which explicitly lists qsv supported options and highlights that global analogues are ignored

Mind that people already started to mix up the things not understanding that there is a custom option for the -bufsize:v - see #36, https://github.com/Intel-Media-SDK/MediaSDK/issues/487, https://github.com/Intel-Media-SDK/MediaSDK/issues/488.

**Comment by lizhong1008** [comment]
@dvrogozh , good check.  There was some historic reasons. I refined some 3.3.1's patches to make sure it can be accepted by community.  
I prefer to add buffersize:v  supported but don't remove the private  option -buffer_size on 3.3.1, to make sure the private option is still compatible.

**Comment by dvrogozh** [comment]
In this way you will need (generally speaking) check consistency between these 2 options if someone will specify them both. This does not mean that I am against this, I just warn...

**Comment by lizhong1008** [comment]
@dvrogozh , it is quite common case. The answer is we just respect the main option instead of the private one. See my commit 8c632d7ec43b457db23b8f51e5d1e366e12d6052.

**Comment by dvrogozh** [comment]
@lizhong1008 :  I am ok with this change. 2 questions:
1. Did you make sure that other key branches in this repository got the fix?
2. I wonder about upstream ffmpeg behavior? will custom -bufffer_size be supported or in the upstream we will go only with -bufsize:v?

**Comment by lizhong1008** [comment]
@dvrogozh ，bufffer_size is never supported in the mainline, so there is no compatibility issue and no additional effort needed. If any users from qsv-3.3.1 switch to mainline want to set bufffer_size, ffmpeg will in interrupt with an error reporting this option is no found.  This is different from current issue: user set -bufsize:v, ffmpeg provide no error/warning but it doesn't take any effect thus we must fix it.

**Comment by dvrogozh** [comment]
@lizhong1008 : let me try to reformulate my question: were you planning to upstream -buffer_size option or in the mainline we will have only -bufsize:v?

**Comment by lizhong1008** [comment]
@dvrogozh , no, we won't upstream the private option "buffer_size", it was wrong way at the very beginning. FFmpeg community would like to use common option as possible, but if a private option already exist we should keep compatibility.

**Comment by dvrogozh** [comment]
@lizhong1008 : cool, that's what I wanted to hear:).
