### ISSUE TITLE
Convert video to image

### ISSUE THREAD

**Issue by ghost** [Intel-FFmpeg-Plugin/Intel_FFmpeg_plugins#49]
I was trying out various flags to convert a video (eg. from rtsp stream) to an image.

The below command works, when dumping to **null**:
`./ffmpeg -hwaccel qsv -c:v h264_qsv -init_hw_device qsv=foo -filter_hw_device foo -rtsp_transport tcp -i rtsp://user:pass@ipaddr:port/Streaming/Channels/101 -f null -`

This is the details about the output format for the above command:

> Stream #0:0: Video: wrapped_avframe, **qsv**, 1920x1080 [SAR 189:190 DAR 168:95], q=2-31, 200 kb/s, 25 fps, 25 tbn, 25 tbc

As seen, the pixel format is qsv. Formatting it to bgr24 etc are computationally expensive. Therefore, I would like to dump the frames in qsv format itself. Is this possible? If yes, what is the file extension? If no, what are the other alternatives to dump to image with very less cpu utilization?

**Comment by lizhong1008** [comment]
@kptikku , sorry for late reply. 
Yes, you can. Please check https://trac.ffmpeg.org/wiki/Hardware/QuickSync for more detail.
