### ISSUE TITLE
what difference is it between qsv-x.x.x and release/x.x?

### ISSUE THREAD

**Issue by andrewmabc** [Intel-FFmpeg-Plugin/Intel_FFmpeg_plugins#5]
Hi,

I have one question about Intel-FFmpeg-Plugin's branches.

There are several active branches, i.e. qsv-3.2.2, qsv-2.8.1, qsv-2.6.3, release/3.3, release/3.2, release/3.1, release/3.0, and release/2.8.

what difference is it between qsv-x.x.x and release/x.x?

Thanks

Regards

andrew

**Comment by hzhan80** [comment]
We re-based our private patches to release/x.x.x and branch it as qsv-x.x.x.  The private patches include new features, bug fix, performance optimization, etc which haven't been upstream. All patches are relative to plugins for Intel HW acceleration.

**Comment by andrewmabc** [comment]
is release/x.x.x indeed ffmpeg offcial branch and just copied from ffmpeg official website?

**Comment by andrewmabc** [comment]
Do you mean, release/x.x.x is indeed ffmpeg offcial branch and just copied from ffmpeg official website, and there are intel patches in branch qsv-x.x.x?

Is that right?

**Comment by hzhan80** [comment]
Yes, you are right.

**Comment by andrewmabc** [comment]
Thanks for your quick response
