### ISSUE TITLE
branch qsv-2.8.1 can't be built successfully without MSDK

### ISSUE THREAD

**Issue by andrewmabc** [Intel-FFmpeg-Plugin/Intel_FFmpeg_plugins#6]
Hi,

I found one problem with branch qsv-2.8.1. If MSDK is installed, the branch can be built successfully. But the branch can't be built successfully if MSDK is not installed.

The test environment is Centos 7.2

Configuration command is shown as follows:
./configure --enable-version3 --enable-asm --enable-yasm --enable-avfilter --disable-static --enable-shared --enable-gpl --prefix=/usr/local/ --extra-cflags=-I/usr/local/include --extra-ldflags=-L/usr/local/lib --enable-nonfree

then make command produce the following compiling error:

CC	libavcodec/qdm2.o
CC	libavcodec/qdrw.o
CC	libavcodec/qpeg.o
CC	libavcodec/qpeldsp.o
CC	libavcodec/qsv_api.o
CC	libavcodec/qsvdec_jpeg.o
In file included from libavcodec/qsvdec_jpeg.c:28:0:
libavcodec/qsvdec.h:29:26: fatal error: mfx/mfxvideo.h: No such file or directory
 #include <mfx/mfxvideo.h>
                          ^
compilation terminated.
make: *** [libavcodec/qsvdec_jpeg.o] Error 1

But the orginal version of ffmpeg-2.8.1 dosen't have the compiling problem.

Looking forward to your help!

Thanks!

Regards

Andrew

**Comment by liuchao8956** [comment]
Hi Andrew,

Thanks for your kindly feedback.
This issue has been fixed by commit 7d7948c1669b407f42c57a45faa75f311f17736f.
