### ISSUE TITLE
qsv decoder doesn't set AVFrame::key_frame and AVFrame::pict_type for branch qsv-2.8.1

### ISSUE THREAD

**Issue by andrewmabc** [Intel-FFmpeg-Plugin/Intel_FFmpeg_plugins#7]
hi,

I used the following command.

/usr/local/bin/ffmpeg -debug_ts -vcodec h264_qsv -i oneClip/bigbang.S06E20.mkv -flags +global_header -f mp4 -vcodec libx264 -acodec libfdk_aac bigbang.S06E20.mp4 >> ./ffmpeg_av_sync_issue.log 2>&1

I found that, qsv decoder doesn't set AVFrame::key_frame and AVFrame::pict_type for branch qsv-2.8.1.

but ffmpeg native h.264 decoder doesn't have the issue.

Regards

Andrew

**Comment by liuchao8956** [comment]
hi Andrew,

You're right about the issue. We doesn't give out the decoded frames' type (I/P/B) at all.
We're now investigating on enabling this feature and will answer you later.

Thanks for your attention.
Chao

**Comment by liuchao8956** [comment]
hi Andrew,

Sorry for no update in such a long time, since we are concentrating on perfecting qsv-3.3.1.

The good news is that we've add the feature that gives out decoded AVFrames' pict_type and key_frame.
Please refer to b4a52a6712619748c44d4ad839ae29460aa466e3 for details.

Thanks,
Chao
